# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory_order.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inventory_order.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inventory_order.proto\x12\x0einventoryorder\"2\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"1\n\x0cStockRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"3\n\rStockResponse\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x03\x41\x63k\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x0cOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0f\n\x07item_id\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"0\n\rOrderResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd5\x01\n\x10InventoryService\x12\x34\n\x07\x41\x64\x64Item\x12\x14.inventoryorder.Item\x1a\x13.inventoryorder.Ack\x12I\n\nCheckStock\x12\x1c.inventoryorder.StockRequest\x1a\x1d.inventoryorder.StockResponse\x12@\n\x0b\x44\x65\x64uctStock\x12\x1c.inventoryorder.StockRequest\x1a\x13.inventoryorder.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_order_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEM']._serialized_start=41
  _globals['_ITEM']._serialized_end=91
  _globals['_STOCKREQUEST']._serialized_start=93
  _globals['_STOCKREQUEST']._serialized_end=142
  _globals['_STOCKRESPONSE']._serialized_start=144
  _globals['_STOCKRESPONSE']._serialized_end=195
  _globals['_ACK']._serialized_start=197
  _globals['_ACK']._serialized_end=235
  _globals['_ORDERREQUEST']._serialized_start=237
  _globals['_ORDERREQUEST']._serialized_end=304
  _globals['_ORDERRESPONSE']._serialized_start=306
  _globals['_ORDERRESPONSE']._serialized_end=354
  _globals['_INVENTORYSERVICE']._serialized_start=357
  _globals['_INVENTORYSERVICE']._serialized_end=570
# @@protoc_insertion_point(module_scope)
